### ISSUE TITLE
Python 2 is failing on Windows

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/icu-feedstock#1]
```shell 
  Started : Saturday, March 26, 2016 3:32:35 PM 
   Source : C:\conda\conda-bld\work\icu\include\ 
     Dest : C:\conda\envs\_build\Library\include\ 
 
    Files : * 
	     
  Options : /S /E /DCOPY:DA /COPY:DAT /R:1000000 /W:30 
 
------------------------------------------------------------------------------
 
2016/03/26 15:32:35 ERROR 2 (0x00000002) Accessing Source Directory C:\conda\conda-bld\work\icu\include\ 
The system cannot find the file specified.
 
C:\conda\conda-bld\work\icu>if 16 LSS 8 exit 0 
Command failed: C:\windows\system32\cmd.exe /c call bld.bat
Command exited with code 1
```

**Comment by msarahan** [comment]
Yeah, known issue.  ICU only provides a VS2010 project file.  More commentary here: https://github.com/conda-forge/staged-recipes/pull/198#issuecomment-201403202

Fix is to use cywing or msys2 to build (these drive VS compilers with their scripts.  It is weird.)

Cygwin recipe at https://github.com/conda-forge/staged-recipes/pull/208 but requires conda-build fix.

**Comment by ocefpaf** [comment]
> Yeah, known issue.  ICU only provides a VS2010 project file.  More commentary here: https://github.com/conda-forge/staged-recipes/pull/198#issuecomment-201403202

Thanks for the xref. I just opened this one to keep track of things.

> Fix is to use cywing or msys2 to build (these drive VS compilers with their scripts.  It is weird.)
> Cygwin recipe at https://github.com/conda-forge/staged-recipes/pull/208 but requires conda-build fix.

Meanwhile how about using AppVeyor's `Cygwin`/`MSYS2`?

**Comment by ocefpaf** [comment]
No also that
    Environment: TARGET_ARCH=x64, CONDA_PY=35
seems to get stuck when it reaches:

```shell
ResourceCompile:
  C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\bin\rc.exe /D NDEBUG /D STUBDATA_BUILD /D _VC80_UPGRADE=0x0710 /l"0x0409" /I../common /nologo /fo".\x64\Release\icudata.res" ..\data\misc\icudata.rc
```

**Comment by msarahan** [comment]
> Meanwhile how about using AppVeyor's Cygwin/MSYS2?

I find this practical, but a moral slippery slope.  Simply listing Cygwin or msys as a pre-requisite for our build platform does not imply any set of packages in those environments.  It's a big headache, IMHO.  The moral fine line is: "Is conda-forge a provider of packages only?" In which case, sure, use appveyor's install, or "Is conda-forge the canonical source of recipes, with CI backing it to improve quality?" - in which case, I think we want to limit our external dependencies as much as possible, especially for things like Cygwin that are non-trivial to get completely right.

I'll try to make it work here, but I'd like to keep a collection of any recipes using cygwin or whatever so that we can go back and fix them when the right solution (I think this is @mingwandroid's split-up MSYS2) is available.

**Comment by ocefpaf** [comment]
> I find this practical, but a moral slippery slope.

I understand that and by no means I want to force that if `ICU` maintainers don't want to go that way. (But I would not hesitate to do so it I needed the binaries in the channel.)

**Comment by ocefpaf** [comment]
I guess that the updates in conda-build fixed this and we missed it. Closing this.
