### ISSUE TITLE
ICU installed in anaconda is an older version than is installed with conda-forge

### ISSUE THREAD

**Issue by katyhuff** [conda-forge/icu-feedstock#12]
See this issue for more details of the symptom: https://github.com/pyne/pyne/issues/866

It was recommended that this issue be created as it may be something that needs to be fixed here in the icu-feedstock repo.

**Comment by ccordoba12** [comment]
You can't install a package that depends on ICU from conda-forge, which in your case is Boost:

https://github.com/conda-forge/pyne-feedstock/blob/master/recipe/meta.yaml#L38

in the root environment. You need to create a new conda environment for that.

---

The problem is not related to the ICU version in conda-forge, but to the fact that conda-forge and the default channels have very different build specifications, which doesn't allow mixing their packages in the same environment.

Please see this comment of mine

https://github.com/conda-forge/boost-feedstock/pull/15#issuecomment-251734905

for a more complete explanation of this point :-)

**Comment by katyhuff** [comment]
Ah, great explanation. Closing this. Thanks!

**Comment by ccordoba12** [comment]
Thanks for understanding :-)
